services:
  - type: web
    name: cookbot-model-server
    env: python
    rootDir: backend/model_server
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.10
      - key: PIP_VERSION
        value: 24.0
    plan: free
    region: singapore

